In [1]:
import numpy as np


In [3]:
a = np.array([2,3])
print(a)

[2 3]


In [6]:
np.linalg.norm(a)

np.float64(3.605551275463989)

In [7]:
#Addition
A = np.array([3,6])
B = np.array([8,9])
A+B

array([11, 15])

In [11]:
A = np.array([3,6])
B = np.array([8,9])
print(np.matmul(A,B))
print(np.dot(A,B))
print(A*B)

78
78
[24 54]


In [13]:
#Scaler Multiplication

A = np.array([5,6])
print(4*A)

[20 24]


In [15]:
A = np.array([3,6])
B = np.array([8,9])
print(np.dot(A,B))

78


In [16]:
#Cosine Similarity
A = np.array([3,6])
B = np.array([8,9])
np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B))


np.float64(0.9656157585206695)

In [18]:
A = np.array([1,0])
B = np.array([0,1])
print(np.dot(A,B))

0


In [19]:
#Vector Projection
A = np.array([3,6])
B = np.array([8,9])
print((np.dot(A,B)/np.dot(B,B))*B)

[4.30344828 4.84137931]


In [21]:
#Check Linear Indipendent of Vectors
A = np.array([3,4])
B= np.array([8,9])
np.linalg.matrix_rank(A,B)

#Rank < No of columns it is dependent


1

In [23]:
A = np.array([3,6])
B = np.array([8,9])
C = 2*A+3*B
print(C)

[30 39]


In [27]:
A = np.array([[3,6,1],[5,9,18],[10,11,66]])
B = np.array([[8,9,87],[27,76,74],[12,53,43]])

C= 2*A+ 3*B
print(C)

print(C.T)

[[ 30  39 263]
 [ 91 246 258]
 [ 56 181 261]]
[[ 30  91  56]
 [ 39 246 181]
 [263 258 261]]


In [28]:
#Determinat
np.linalg.det(C)


np.float64(871208.0000000009)

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
A = np.array([[3,6,1],[5,9,18],[10,11,66]])
B = np.array([[8,9,87],[27,76,74],[12,53,43]])
print(np.linalg.inv(A))
print()
print(np.linalg.inv(B))


[[ 1.56521739 -1.52173913  0.39130435]
 [-0.59288538  0.743083   -0.19367589]
 [-0.13833992  0.10671937 -0.01185771]]

[[-0.01745676  0.11274824 -0.15871236]
 [-0.007287   -0.0186846   0.04689836]
 [ 0.0138533  -0.00843476  0.00974269]]


In [32]:
A = np.array([[3,6,1],[5,9,18],[10,11,66]])
np.linalg.matrix_rank(A)

np.int64(3)

In [33]:
#Trace
np.trace(A)

np.int64(78)

In [34]:
np.all(A==A.T)

np.False_

In [40]:
import numpy as np

A = np.array([[1,1,1],
              [1,3,4]])

print(np.all(A == A.T))

B = np.array([[1,2,3],
              [3,4,5]])

print(np.all(B == B.T))

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [43]:
B= np.array([[3,1],[2,1]])
t = np.linalg.eig(B)
print(t)

EigResult(eigenvalues=array([3.73205081, 0.26794919]), eigenvectors=array([[ 0.80689822, -0.34372377],
       [ 0.59069049,  0.9390708 ]]))


In [44]:
from sympy import symbols,diff

In [46]:
#Derivative
x= symbols('x')
diff(x**2+3*x)

2*x + 3

In [47]:
from sympy import symbols, diff

x, y = symbols('x y')

expr = x**2 + y**2 + 3*y + 2*x

# derivative w.r.t x
dx = diff(expr, x)

# derivative w.r.t y
dy = diff(expr, y)

print("d/dx:", dx)
print("d/dy:", dy)

d/dx: 2*x + 2
d/dy: 2*y + 3


In [48]:
from sympy import symbols, Matrix
f= x**2+y**2
Matrix(diff(f,x),diff(f,y))
